# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'joseph.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    wallhack = False
    trigger = False
    bhop = False
    noflash = False
    radar = False

    def trigger(self):
        print("trigger")
        if (self.trigger == True):
            self.trigger = False
        else:
            self.trigger = True

        if (self.trigger == True):

            self.pushButton_8.setStyleSheet("image: url(:/newPrefix/flagGreenturkey.png);background-image: url(:/newPrefix/dark.jpg);")
        else:
            self.pushButton_8.setStyleSheet("image: url(:/newPrefix/220px-Flag_of_Turkey.jpg);background-image: url(:/newPrefix/dark.jpg);")

        if (self.wallhack==True and self.trigger==True and self.bhop==True and self.noflash==True and self.radar==True):
            print("ULTRA INSTINCT")
            MainWindow.setStyleSheet("background-image: url(:/newPrefix/ultrabeeg.jpeg);")
        else:
            MainWindow.setStyleSheet("background-image: url(:/newPrefix/beeg.jpg);")


    def bhop(self):
        print("bhop")
        if (self.bhop == True):
            self.bhop = False
        else:
            self.bhop = True

        if (self.bhop == True):

            self.pushButton_7.setStyleSheet("image: url(:/newPrefix/flagGreenturkey.png);background-image: url(:/newPrefix/dark.jpg);")
        else:
            self.pushButton_7.setStyleSheet("image: url(:/newPrefix/220px-Flag_of_Turkey.jpg);background-image: url(:/newPrefix/dark.jpg);")
        if (self.wallhack==True and self.trigger==True and self.bhop==True and self.noflash==True and self.radar==True):
            print("ULTRA INSTINCT")
            MainWindow.setStyleSheet("background-image: url(:/newPrefix/ultrabeeg.jpeg);")
        else:
            MainWindow.setStyleSheet("background-image: url(:/newPrefix/beeg.jpg);")


    def wallhack(self):
        print("wallhack")
        if (self.wallhack == True):
            self.wallhack = False
        else:
            self.wallhack = True

        if (self.wallhack == True):

            self.pushButton_3.setStyleSheet("image: url(:/newPrefix/flagGreenturkey.png);background-image: url(:/newPrefix/dark.jpg);")
        else:
            self.pushButton_3.setStyleSheet("image: url(:/newPrefix/220px-Flag_of_Turkey.jpg);background-image: url(:/newPrefix/dark.jpg);")
        if (self.wallhack==True and self.trigger==True and self.bhop==True and self.noflash==True and self.radar==True):
            print("ULTRA INSTINCT")
            MainWindow.setStyleSheet("background-image: url(:/newPrefix/ultrabeeg.jpeg);")
        else:
            MainWindow.setStyleSheet("background-image: url(:/newPrefix/beeg.jpg);")


        # self.wallhack=false

    def noflash(self):
        print("noflash")
        if (self.noflash == True):
            self.noflash = False
        else:
            self.noflash = True

        if (self.noflash == True):

            self.pushButton_4.setStyleSheet("image: url(:/newPrefix/flagGreenturkey.png);background-image: url(:/newPrefix/dark.jpg);")
        else:
            self.pushButton_4.setStyleSheet("image: url(:/newPrefix/220px-Flag_of_Turkey.jpg);background-image: url(:/newPrefix/dark.jpg);")
        if (self.wallhack==True and self.trigger==True and self.bhop==True and self.noflash==True and self.radar==True):
            print("ULTRA INSTINCT")
            MainWindow.setStyleSheet("background-image: url(:/newPrefix/ultrabeeg.jpeg);")
        else:
            MainWindow.setStyleSheet("background-image: url(:/newPrefix/beeg.jpg);")


    def radar(self):

        print("radar")
        if (self.radar == True):
            self.radar = False
        else:
            self.radar = True

        if (self.radar == True):

            self.pushButton_6.setStyleSheet("image: url(:/newPrefix/flagGreenturkey.png);background-image: url(:/newPrefix/dark.jpg);")
        else:
            self.pushButton_6.setStyleSheet("image: url(:/newPrefix/220px-Flag_of_Turkey.jpg);background-image: url(:/newPrefix/dark.jpg);")
        if (self.wallhack==True and self.trigger==True and self.bhop==True and self.noflash==True and self.radar==True):
            print("ULTRA INSTINCT")
            MainWindow.setStyleSheet("background-image: url(:/newPrefix/ultrabeeg.jpeg);")
        else:
            MainWindow.setStyleSheet("background-image: url(:/newPrefix/beeg.jpg);")


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(736, 429)
        MainWindow.setStyleSheet("background-image: url(:/newPrefix/beeg.jpg);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(11)

        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(530, 0, 141, 51))
        self.pushButton_3.setStyleSheet("image: url(:/newPrefix/220px-Flag_of_Turkey.jpg);background-image: url(:/newPrefix/dark.jpg);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.wallhack)
        self.pushButton_3.setFont(font)

        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(530, 70, 141, 51))
        self.pushButton_4.setStyleSheet("image: url(:/newPrefix/220px-Flag_of_Turkey.jpg);background-image: url(:/newPrefix/dark.jpg);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(self.noflash)
        self.pushButton_4.setFont(font)

        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(530, 140, 141, 51))
        self.pushButton_6.setStyleSheet("image: url(:/newPrefix/220px-Flag_of_Turkey.jpg);background-image: url(:/newPrefix/dark.jpg);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_6.clicked.connect(self.radar)
        self.pushButton_6.setFont(font)

        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(530, 210, 141, 51))
        self.pushButton_7.setStyleSheet("image: url(:/newPrefix/220px-Flag_of_Turkey.jpg);background-image: url(:/newPrefix/dark.jpg);")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_7.clicked.connect(self.bhop)
        self.pushButton_7.setFont(font)

        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(530, 280, 141, 51))

        self.pushButton_8.setStyleSheet("image: url(:/newPrefix/220px-Flag_of_Turkey.jpg);background-image: url(:/newPrefix/dark.jpg);")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_8.clicked.connect(self.trigger)
        self.pushButton_8.setFont(font)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 736, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        MainWindow.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))

       # self.pushButton_3.setToolTip(_translate("MainWindow",
                                               # "<html><head/><body><p><img src=\":/newPrefix/220px-Flag_of_Turkey.jpg\"/></p></body></html>"))
        self.pushButton_3.setText(_translate("MainWindow", "Wallhack"))
       # self.pushButton_4.setToolTip(_translate("MainWindow",
                                               # "<html><head/><body><p><img src=\":/newPrefix/220px-Flag_of_Turkey.jpg\"/></p></body></html>"))
        self.pushButton_4.setText(_translate("MainWindow", "NoFlash"))
        #self.pushButton_6.setToolTip(_translate("MainWindow",
                                               # "<html><head/><body><p><img src=\":/newPrefix/220px-Flag_of_Turkey.jpg\"/></p></body></html>"))
        self.pushButton_6.setText(_translate("MainWindow", "RadarHack"))
       # self.pushButton_7.setToolTip(_translate("MainWindow",
                                              #  "<html><head/><body><p><img src=\":/newPrefix/220px-Flag_of_Turkey.jpg\"/></p></body></html>"))
        self.pushButton_7.setText(_translate("MainWindow", "BHOP"))
        #self.pushButton_8.setToolTip(_translate("MainWindow",
                                               # "<html><head/><body><p><img src=\":/newPrefix/220px-Flag_of_Turkey.jpg\"/></p></body></html>"))
        self.pushButton_8.setText(_translate("MainWindow", "Trigger"))


import resource_rc

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
